### ISSUE TITLE
is not a valid value for options.access. The valid values are: ["container","blob"].

### ISSUE THREAD

**Issue by lgmorand** [tibor19/static-website-deploy#9]
Hi @tibor19 

I just upgraded a working workflow from v1 to v2 and now, I get a weird error: 

`Error:  is not a valid value for options.access. The valid values are: ["container","blob"].
    at serializeEnumType (/home/runner/work/_actions/tibor19/static-website-deploy/v2/dist/index.js:2634:15)
    at Serializer.serialize (/home/runner/work/_actions/tibor19/static-website-deploy/v2/dist/index.js:2405:27)
    at getOperationArgumentValueFromParameterPath (/home/runner/work/_actions/tibor19/static-website-deploy/v2/dist/index.js:6897:24)
    at getOperationArgumentValueFromParameter (/home/runner/work/_actions/tibor19/static-website-deploy/v2/dist/index.js:6868:12)
    at StorageClientContext.sendOperationRequest (/home/runner/work/_actions/tibor19/static-website-deploy/v2/dist/index.js:6622:39)
    at Container.setAccessPolicy (/home/runner/work/_actions/tibor19/static-website-deploy/v2/dist/index.js:18899:28)
    at ContainerClient.setAccessPolicy (/home/runner/work/_actions/tibor19/static-website-deploy/v2/dist/index.js:30380:48)
    at main (/home/runner/work/_actions/tibor19/static-website-deploy/v2/dist/index.js:50698:32)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)`

https://github.com/lgmorand/workshop-aca/actions/runs/3938050173/jobs/6736280406#step:8:27

any idea?

**Comment by lgmorand** [comment]
When I revert to V1, the workflow works perfectly.

**Comment by tibor19** [comment]
I am not sure if this was a mistake from my part or if the interface has changed since I released v1. I need to decide if I should keep the interface the same or modify it to map to the new interface.

**Comment by lgmorand** [comment]
```javascript
const accessPolicy = getInput('public-access-policy');
```

And since the parameter is optional

```yaml
public-access-policy: 
    description: 'Access Policy to update in the Container (BlobContainer | Blob | None). For private containers do not specity any value.'
    required: false
```

Looks like "None" or empty is not accepted anymore. I manually  specified "Container" and it worked.

**Comment by lgmorand** [comment]
Your fix does not seem to work: https://github.com/lgmorand/aks-workshop/actions/runs/3949181036/jobs/6760068389

**Comment by lgmorand** [comment]
It seems they removed "none" as an option: https://github.com/Azure/azure-sdk-for-js/blob/c2d8a5c107a1b9b04812727cff45722ff3148964/sdk/storage/storage-blob/src/ContainerClient.ts#L93

But on other SDK, the option is still valid: https://learn.microsoft.com/cs-cz/dotnet/api/azure.storage.blobs.blobcontainerclient.setaccesspolicy?view=azure-dotnet

**Comment by tibor19** [comment]
@lgmorand I fixed it. Can you try it again?

**Comment by tibor19** [comment]
> Your fix does not seem to work: https://github.com/lgmorand/aks-workshop/actions/runs/3949181036/jobs/6760068389

The reason it didn't work was because I forgot to build the code before deployment! :)

**Comment by lgmorand** [comment]
@tibor19 it's a success Sir ! :)
https://github.com/lgmorand/aks-workshop/actions/runs/3956486273/jobs/6775756778

I'll now switch back to v2 since you updated the tag. Thanks a lot for the quick fix

**Comment by lgmorand** [comment]
hum. with v2, it does not work
https://github.com/lgmorand/aks-workshop/actions/runs/3956509578/jobs/6775806296

**Comment by lgmorand** [comment]
![image](https://user-images.githubusercontent.com/6757079/213389355-80e8c277-44c8-44dc-ab4a-627f3ff5c475.png)
oh that's a tricky move. you updated the release but not the tag :)

**Comment by tibor19** [comment]
Fixed! :)

**Comment by lgmorand** [comment]
this time, it works !
